# vim:set ft=yaml ts=4 sw=4 sts=4 autoindent:

# Configuration file for Travis CI continuous integration.
#
# Author:   Pontus Stenetorp    <pontus stenetorp se>
# Version:  2014-12-20

language: julia
julia:
    - release
    - nightly
matrix:
    fast_finish: true
notifications:
    email: false
after_success: |
    julia -e 'Pkg.add("Coverage")'
    julia -e 'cd(Pkg.dir("Hinton")); using Coverage;
        Coveralls.submit(Coveralls.process_folder())'
